WARNING: No test specified, defaulting to first test defined (_)
TRACE: Initialized test input buffer with data from `/home/akhila/fuzzer_packages/fuzzedpackages/midasml/inst/testfiles/cvfolds/cvfolds_output/2933719dc74e96a12995827905fce0809c41dde9.fail`
TRACE: Running: _ from /home/akhila/fuzzer_packages/fuzzedpackages/midasml/inst/testfiles/cvfolds/cvfolds_DeepState_TestHarness.cpp(13)
input starts
EXTERNAL: qs v0.23.5.

nfolds values: -1.5615e-299
nrow values: -1.20777e+13
input ends

error: Col::subvec(): indices out of bounds or incorrectly used
terminate called after throwing an instance of 'std::logic_error'
  what():  Col::subvec(): indices out of bounds or incorrectly used
ERROR: Failed: _
ERROR: Test case /home/akhila/fuzzer_packages/fuzzedpackages/midasml/inst/testfiles/cvfolds/cvfolds_output/2933719dc74e96a12995827905fce0809c41dde9.fail failed
