WARNING: No test specified, defaulting to first test defined (_)
TRACE: Initialized test input buffer with data from `/home/akhila/fuzzer_packages/fuzzedpackages/midasml/inst/testfiles/cvfolds/cvfolds_output/9be2e84527303d576bf8fbd05c45d5e60d9e5d37.fail`
TRACE: Running: _ from /home/akhila/fuzzer_packages/fuzzedpackages/midasml/inst/testfiles/cvfolds/cvfolds_DeepState_TestHarness.cpp(13)
input starts
EXTERNAL: qs v0.23.5.

nfolds values: 3.16522e+06
nrow values: 3.72126e-82
input ends

error: Col::subvec(): indices out of bounds or incorrectly used
terminate called after throwing an instance of 'std::logic_error'
  what():  Col::subvec(): indices out of bounds or incorrectly used
ERROR: Failed: _
ERROR: Test case /home/akhila/fuzzer_packages/fuzzedpackages/midasml/inst/testfiles/cvfolds/cvfolds_output/9be2e84527303d576bf8fbd05c45d5e60d9e5d37.fail failed
